Repository elementary/switchboard-plug-datetime, pull requests merged in 2018-10, with the labels that each got.

#45 Center valign switches
  src/Plug.vala
Labels: Bitesize

#46 Plug search improvements
  src/Plug.vala
Labels: Status: Blocked

#48 More robust error handling around timezones and cities
  src/Parser.vala
  src/Widgets/TimeZoneButton.vala
Labels: Priority: High
